name: Swift

on: [push]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  Linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.1
    steps:
      - uses: actions/checkout@v1
      - run: swift test
